language: node_js
node_js: "10"
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  verbose: true
  on:
    branch: master
