name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@2.0.3
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm ci && npm run-script build
